services:
  bot:
    build: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - DATABASE_URL=postgresql://user:password@db:5432/shamebot
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shamebot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
